# name: Continuous Integration

# on:
#   push:
#     branches:
#       - main

# jobs:
#   build:
#     runs-on: windows-latest

#     steps:
#       - name: Checkout Repository
#         uses: actions/checkout@v4 # Update to use the latest version of actions/checkout

#       - name: Set up Node.js
#         uses: actions/setup-node@v4 # Update to use the latest version of actions/setup-node
#         with:
#           node-version: '14'

#       - name: Install Dependencies
#         run: npm install

#       - name: Load Environment Variables
#         run: npm test
#         env:
#           MONGODB_URL: ${{ secrets.MONGODB_URL }}
          

name: Node.js CI/CD

on:
  push:
    branches: [ main ]
  
jobs:
  build:

    runs-on: windows-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v4 
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - name: Run tests
      env:
        MONGODB_URL: ${{ secrets.MONGODB_URL }}
      run: npm test
